### ISSUE TITLE
Cmoa.jp图片拼接存在问题

### ISSUE THREAD

**Issue by zhongfly** [vircoys/ccdl#1]
cmoa网站是将一张漫画图片分成3小图，并且每张小图间有重复行。目前代码中是对此做了自动判断，但这部分代码存在bug，会导致切除未重复的部分。
而且，https://github.com/vircoys/ccdl/blob/master/src/ccdl/binb.py#L156 已经固定了图片高度，不随前述代码获得的重复行有关。
经测试，固定ij=4即可

如图，1/3和2/3处明显缺失，并且图片底部有黑边。
![1](https://user-images.githubusercontent.com/11155705/95155657-368c9000-07c7-11eb-99c5-368ccfa1236f.png)

**Comment by vircoys** [comment]
ij的值对于同一网站的不同漫画都不一定通用，还是需要计算，对于同一分辨率的图像可能可以使用同一值。
下次更新Cmoa的采集将不再依赖selenium。
该bug近期应该不会修复。

**Comment by zhongfly** [comment]
> ij的值对于同一网站的不同漫画都不一定通用，还是需要计算，对于同一分辨率的图像可能可以使用同一值。
> 下次更新Cmoa的采集将不再依赖selenium。
> 该bug近期应该不会修复。

目前这张图片至少说明ij的计算判断是存在问题的，希望能够修复。

**Comment by vircoys** [comment]
我尽快，下更新后会解决，图像质量也会好一些
![image](https://user-images.githubusercontent.com/40519857/95588157-a45de380-0a75-11eb-9345-2dcdf3e0a136.png)

**Comment by zhongfly** [comment]
关于是否是否通用这一问题，目前我尝试下载了多种不同分辨率的不同漫画，尚未出现ij=4不适用的情况。

你现在是要要自己实现图片拼接还原吗？目前用selenium下载速度并不快，还是挺期待不依赖它的方法。

**Comment by vircoys** [comment]
在binb.py中的类Binb2使拼接异常问题得到解决

**Comment by zhongfly** [comment]
> 在binb.py中的类Binb2使拼接异常问题得到解决

然而不能登录了（在chrome中登录无效）

**Comment by vircoys** [comment]
最近找实习，没什么时间写登录模块，估计一周后吧

**Comment by vircoys** [comment]
支持cmoa在浏览器登录，png格式会导致传输成本增加，目测压不压没太大区别

**Comment by vircoys** [comment]
binb系阅读器采集的合图异常应该是修复了
