### ISSUE TITLE
关于comic-action类似网站

### ISSUE THREAD

**Issue by zhongfly** [vircoys/ccdl#2]
从该网站js中可以发现，有不少网站和它是使用同一套框架
 "jump_plus": "https://shonenjumpplus.com",
 "tonarino_yj": "https://tonarinoyj.jp",
 "magapoke": "https://pocket.shonenmagazine.com",
 "comicdays": "https://comic-days.com",
 "kuragebunch": "https://kuragebunch.com",
 "smaga": "https://shonenmagazine.com",
 "heros": "https://viewer.heros-web.com",
 "border": "https://comicborder.com",
 "gardo": "https://comic-gardo.com",
 "zenon": "https://comic-zenon.com",
 "magcomi": "https://magcomi.com",
 "action": "https://comic-action.com"

章节信息（json）可以从章节链接后添加.json获得。
https://comic-action.com/episode/13933686331726991964 的json信息：https://comic-action.com/episode/13933686331726991964.json

漫画的全部章节，可从网页源代码中的rss链接获得
```
<link rel="alternate" type="application/atom+xml" title="Atom" href="https://comic-action.com/atom/series/13933686331723869587">
<link rel="alternate" type="application/rss+xml" title="RSS2.0" href="https://comic-action.com/rss/series/13933686331723869587">

```

**Comment by vircoys** [comment]
部分网站需要登录，获取章节信息暂时用通用的方法；
目前优先实现字典 [_site_reader](https://github.com/vircoys/ccdl/blob/master/src/ccdl/utils.py#L15) 记录的网站（需求）；
章节探测、自动采集、数据记录等功能不会在此项目中实现。

**Comment by vircoys** [comment]
已添加支持，并移除部分站点对webdriver的依赖

**Comment by zhongfly** [comment]
我又有了新发现，手机UA下，返回的json中图片是不需要重组（或者说解密、还原）的。
例如电脑ua返回的是：
`https://cdn-img.tonarinoyj.jp/public/page/2/13933686331773465515-294d0d623a90ee61d66fe60408a87026`
而手机UA则是：
`https://cdn-img.tonarinoyj.jp/public/original/13933686331773465515-71d82b804f35c051d0db25f44746ca73`
测试使用的手机UA为：`Mozilla/5.0 (Linux; Android 10; ONEPLUS A5000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36`

**Comment by vircoys** [comment]
看起来是这样
