### ISSUE TITLE
CCSimpleStarter can't download

### ISSUE THREAD

**Issue by icebearcomic** [vircoys/ccdl#7]
When i run CCSimpleStarter.py and add booklive.jp link, it's back
Traceback (most recent call last):
  File "CcdlSimpleStarter.py", line 59, in <module>
  File "ccdl\binb.py", line 422, in downloader
AttributeError: 'NoneType' object has no attribute 'get'

Please help me, thank you

**Comment by vircoys** [comment]
It seems that there is no chromedriver. Please download a chromedriver that matches your chrome version.

**Comment by icebearcomic** [comment]
> It seems that there is no chromedriver. Please download a chromedriver that matches your chrome version.

tks for your response. I installed chromedriver and put chromedrive.exe in the same folder with CCsimplestarter.exe and run it, it's still error.

源碼: https://github.com/vircoys/ccdl

如需登入（含*）請提前在程式啟動的瀏覽器中登入，並加載目標url（任意標籤頁）！


DevTools listening on ws://127.0.0.1:1962/devtools/browser/c2358b7b-1fc5-4e47-ad85-79fbecbb6d1c

>>>>>>>>輸入exit退出<<<<<<<<

url: [11012:7588:0319/180626.061:ERROR:device_event_log_impl.cc(214)] [18:06:26.053] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
https://booklive.jp/product/index/title_id/832389/vol_no/001
下載失敗!
Traceback (most recent call last):
  File "CcdlSimpleStarter.py", line 59, in <module>
  File "ccdl\binb.py", line 425, in downloader
  File "selenium\webdriver\support\wait.py", line 80, in until
selenium.common.exceptions.TimeoutException: Message: 漫画加载超时

**Comment by vircoys** [comment]
If the auto open browser window cannot load the web page, try using a proxy such as v2rayng. 
（可能是网络问题）

**Comment by vircoys** [comment]
Supported URLs such as "https://booklive.jp/bviewer/s/?cid=921042_001&rurl=https%3A%2F%2Fbooklive.jp%2Fproduct%2Findex%2Ftitle_id%2F832389%2Fvol_no%2F001"

**Comment by icebearcomic** [comment]
> Supported URLs such as "https://booklive.jp/bviewer/s/?cid=921042_001&rurl=https%3A%2F%2Fbooklive.jp%2Fproduct%2Findex%2Ftitle_id%2F832389%2Fvol_no%2F001"

tks for your help, with that URL, i've downloaded. Thank you very much!

**Comment by icebearcomic** [comment]
one more question, can i download purchase chapter?

**Comment by vircoys** [comment]
You can try it, but please login in the browser first, then click the chapter you need, and finally enter the URL of the chapter.

**Comment by icebearcomic** [comment]
> You can try it, but please login in the browser first, then click the chapter you need, and finally enter the URL of the chapter.

i will try it and feedback soon. Thank you!

**Comment by icebearcomic** [comment]
> Log in to the website in the automatically opened browser and open the corresponding chapter webpage link.

It works perfectly :D
